server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://milodb.cawvfuk3bcql.ap-northeast-2.rds.amazonaws.com/baemin_v2?useSSL=false&autoReconnect=true # 변경해주세요
    username: milo # 변경해주세요
    password: 30sec2mars! # 변경해주세요
    #driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    driver-class-name: com.mysql.jdbc.Driver # mysql 5버전